import { burgerFlatlistImg, burgerFlatListImg } from './index';

export const loginRedBg = require('./images/loginRed.png');
export const loginFoodPlateBg = require('./images/foodPlate.png');
export const phoneIcon = require('./images/phoneIcon.png');
export const downArrowIcon = require('./images/arrowLeft.png');
export const spalshScreen1 = require('../assets/images/Splash1.png');
export const spalshScreen2 = require('../assets/images/Splash2.png');
export const onBoardingScreen1 = require('../assets/images/OnBoarding1.jpg');
export const onBoardingScreen2 = require('../assets/images/OnBoarding2.jpg');
export const onBoardingScreen3 = require('../assets/images/OnBoarding3.jpg');
export const onBoardingScreen4 = require('../assets/images/OnBoarding4.jpg');
export const circleImg = require('../assets/images/Circle.png');
export const continueBtn = require('../assets/images/Continuebtn.png');
export const loginBg = require('../assets/images/Loginbg.png');
export const loginImg = require('../assets/images/LoginImg.png');
export const customerImg = require('../assets/images/Customer.png');
export const sellerImg = require('../assets/images/Seller.png');
export const registerImg = require('../assets/images/RegisterImg.png');
export const registerTopImg = require('../assets/images/registerBg.png');
export const personImg = require('../assets/images/Person.png');
export const otpEmailImg = require('../assets/images/OtpEmailImg.png');
export const otpBgImg = require('../assets/images/otpBanner.png');
export const resendIconImg = require("../assets/images/resendIcon.png");
export const allowLocationImg = require("../assets/images/allowLocationImg.png");
export const forgotPasscodeImg = require("../assets/images/ForgotPasscodeBg.png");
export const questionMarkImg = require("../assets/images/QuestionMark.png");
export const otpVerifiForgotPassBgImg = require("../assets/images/OtpVerificationForgotPassBg.png");
export const userProfileImg = require("../assets/images/userProfile.png");
export const pizzaImg = require("../assets/images/pizza.png");
export const chickenImg = require("../assets/images/chicken.png");
export const homeCarouselImg = require("../assets/images/homeCarouselImg.png");
export const bestChoiceBurgerImg = require("../assets/images/bestChoiceBurger.png");
export const bestChoiceBellIconImg = require("../assets/images/bestChoiceBellIcon.png");
export const plusIconImg = require("../assets/images/plusIcon.png");
export const todaySpecialImg = require("../assets/images/TodaySpecialImg.png");
export const dishImg = require("../assets/images/dish.png");
export const restaurantNearByImg = require("../assets/images/restaurantNearByHome.png");
export const burgerPizzaImg = require("../assets/images/burgerPizza.png");
export const offersBannerOneImg = require("../assets/images/offersBanner1.png");
export const offersBannerTwoImg = require("../assets/images/offersBanner2.png");
export const offersBannerThreeImg = require("../assets/images/offersBanner3.png");
export const ellipseImg = require("../assets/images/ellipseImg.png");
export const targetImg = require("../assets/images/targetImg.png");
export const arrowBackImg = require("../assets/images/arrowBack.png");
export const offerCarouselHeaderImg = require("../assets/images/offerCarouselHeader.png");
export const notifiEllipseImg = require("../assets/images/notifiEllipse.png");
export const tickImg = require("../assets/images/tick.png");
export const shoppingBagImg = require("../assets/images/shoppingBag.png");
export const editProfileImg = require("../assets/images/editProfileImg.png");
export const favoriteImg = require("../assets/images/favoriteImg.png");



